// Code generated by Icestudio 0.6.0

`default_nettype none

//---- Top entity
module main #(
 parameter v2bd788 = "v2bd788.list",
 parameter vae97e5 = 12000000*(0.25),
 parameter vaf723e = 12000000*(1),
 parameter v74b45a = 12000000*(0.25),
 parameter va84d84 = 12000000*(1)
) (
 input v745411,
 input vcc3aaf,
 input v61265d,
 input vclk,
 output vd7e736,
 output v148b0b,
 output vfbf5cf,
 output v3825d5,
 output v29fa37,
 output v578e7d,
 output v86bcf0,
 output v9659d8,
 output vf62064,
 output v285cf1,
 output v288f6a,
 output v1de362,
 output vc4787f,
 output v632df3,
 output v97c4df,
 output v745e78
);
 localparam p21 = v2bd788;
 localparam p22 = vae97e5;
 localparam p25 = vaf723e;
 localparam p29 = v74b45a;
 localparam p32 = va84d84;
 wire w0;
 wire w1;
 wire w2;
 wire [0:7] w3;
 wire w4;
 wire w5;
 wire w6;
 wire w7;
 wire w8;
 wire [0:7] w9;
 wire w10;
 wire w11;
 wire w12;
 wire w13;
 wire w14;
 wire w15;
 wire w16;
 wire w17;
 wire w18;
 wire [0:3] w19;
 wire [0:3] w20;
 wire w23;
 wire w24;
 wire w26;
 wire w27;
 wire w28;
 wire w30;
 wire w31;
 wire w33;
 wire w34;
 wire w35;
 wire w36;
 wire w37;
 wire w38;
 wire w39;
 wire w40;
 wire w41;
 wire w42;
 wire w43;
 wire w44;
 wire w45;
 wire w46;
 wire w47;
 wire w48;
 wire w49;
 wire w50;
 wire w51;
 wire w52;
 wire w53;
 wire w54;
 wire w55;
 wire w56;
 wire w57;
 wire w58;
 wire w59;
 wire w60;
 wire w61;
 wire w62;
 wire w63;
 wire w64;
 assign w6 = v745411;
 assign w7 = vcc3aaf;
 assign w8 = v61265d;
 assign vf62064 = w12;
 assign v285cf1 = w13;
 assign v288f6a = w14;
 assign v1de362 = w15;
 assign vc4787f = w23;
 assign v632df3 = w26;
 assign v97c4df = w30;
 assign v745e78 = w33;
 assign w36 = vclk;
 assign w37 = vclk;
 assign w38 = vclk;
 assign w39 = vclk;
 assign w40 = vclk;
 assign w41 = vclk;
 assign w42 = vclk;
 assign w43 = vclk;
 assign w44 = vclk;
 assign w45 = vclk;
 assign w46 = vclk;
 assign v3825d5 = w47;
 assign vfbf5cf = w49;
 assign v86bcf0 = w51;
 assign v29fa37 = w53;
 assign v578e7d = w55;
 assign vd7e736 = w59;
 assign v148b0b = w63;
 assign w37 = w36;
 assign w38 = w36;
 assign w38 = w37;
 assign w39 = w36;
 assign w39 = w37;
 assign w39 = w38;
 assign w40 = w36;
 assign w40 = w37;
 assign w40 = w38;
 assign w40 = w39;
 assign w41 = w36;
 assign w41 = w37;
 assign w41 = w38;
 assign w41 = w39;
 assign w41 = w40;
 assign w42 = w36;
 assign w42 = w37;
 assign w42 = w38;
 assign w42 = w39;
 assign w42 = w40;
 assign w42 = w41;
 assign w43 = w36;
 assign w43 = w37;
 assign w43 = w38;
 assign w43 = w39;
 assign w43 = w40;
 assign w43 = w41;
 assign w43 = w42;
 assign w44 = w36;
 assign w44 = w37;
 assign w44 = w38;
 assign w44 = w39;
 assign w44 = w40;
 assign w44 = w41;
 assign w44 = w42;
 assign w44 = w43;
 assign w45 = w36;
 assign w45 = w37;
 assign w45 = w38;
 assign w45 = w39;
 assign w45 = w40;
 assign w45 = w41;
 assign w45 = w42;
 assign w45 = w43;
 assign w45 = w44;
 assign w46 = w36;
 assign w46 = w37;
 assign w46 = w38;
 assign w46 = w39;
 assign w46 = w40;
 assign w46 = w41;
 assign w46 = w42;
 assign w46 = w43;
 assign w46 = w44;
 assign w46 = w45;
 assign w48 = w47;
 assign w50 = w49;
 assign w52 = w51;
 assign w54 = w53;
 assign w56 = w55;
 assign w57 = w55;
 assign w57 = w56;
 assign w58 = w55;
 assign w58 = w56;
 assign w58 = w57;
 assign w60 = w59;
 assign w61 = w59;
 assign w61 = w60;
 assign w62 = w59;
 assign w62 = w60;
 assign w62 = w61;
 assign w64 = w63;
 v89d234 v4da56c (
  .vf892a0(w2),
  .v39f831(w3),
  .vb1c024(w9),
  .v41eb95(w36)
 );
 v53847c v367d3b (
  .vd50ef8(w3),
  .v7d29fb(w4),
  .v3ba3e6(w5),
  .v4a6801(w37)
 );
 vdc93d6 v250fec (
  .v3c12b5(w5),
  .ve7f5e6(w6),
  .v717e81(w38)
 );
 vdc93d6 v7a22ba (
  .v3c12b5(w0),
  .ve7f5e6(w7),
  .v717e81(w39)
 );
 vdc93d6 v81365f (
  .v3c12b5(w1),
  .ve7f5e6(w8),
  .v717e81(w40)
 );
 v31e84e v49e8b5 (
  .ve78ab8(w0),
  .v3487af(w4),
  .ved8395(w41)
 );
 v31e84e v9489a8 (
  .ve78ab8(w1),
  .v3487af(w2),
  .ved8395(w42)
 );
 vbc6704 v46df35 (
  .v595263(w9),
  .ve0c1b4(w47),
  .v7c37b3(w49),
  .v7ada3f(w51),
  .v2c9812(w53),
  .v45ab8c(w55),
  .vb85197(w59),
  .v8f149e(w63)
 );
 vb2090f vf20b11 (
  .vcbab45(w17),
  .v0e28cb(w57),
  .v3ca442(w60)
 );
 vb2090f v9e549b (
  .v3ca442(w10),
  .vcbab45(w18),
  .v0e28cb(w56)
 );
 v35f267 v40aff7 (
  .vcbab45(w10),
  .v0e28cb(w61)
 );
 vb2090f v24d53e (
  .v0e28cb(w11),
  .vcbab45(w16),
  .v3ca442(w62)
 );
 v35f267 vc98f3a (
  .vcbab45(w11),
  .v0e28cb(w58)
 );
 v45c913 v72e6fd (
  .v5b73e8(w12),
  .vc90115(w13),
  .v2812a7(w14),
  .v593f43(w15),
  .v930b03(w20)
 );
 vd8f675 v5cd271 (
  .v03aaf0(w16),
  .vee8a83(w17),
  .v1311d2(w18),
  .v5d9ba2(w19),
  .v77b6c4(w64)
 );
 v766f27 #(
  .vb36a78(p21)
 ) vb1e8fc (
  .v851180(w19),
  .vfde47f(w20)
 );
 vbce541 #(
  .va04f5d(p22)
 ) v31a8d3 (
  .v6dda25(w43)
 );
 ve108d0 v9fe4e0 (
  .v8f3bff(w23),
  .v0e9572(w24),
  .vaf813b(w48)
 );
 v725b7e v509bb7 (
  .v9fb85f(w24)
 );
 vbce541 #(
  .va04f5d(p25)
 ) vf90444 (
  .v4642b6(w27),
  .v6dda25(w44)
 );
 vf72b3a vdc6b84 (
  .vc93bbe(w26),
  .v381ebf(w27),
  .vb186da(w28),
  .v50d6c6(w50)
 );
 v21cfcc v26beb4 (
  .v9fb85f(w28)
 );
 vbce541 #(
  .va04f5d(p29)
 ) v10e948 (
  .v6dda25(w45)
 );
 ve108d0 v5f78e3 (
  .v8f3bff(w30),
  .v0e9572(w31),
  .vaf813b(w52)
 );
 v725b7e v871a54 (
  .v9fb85f(w31)
 );
 vbce541 #(
  .va04f5d(p32)
 ) v52c10c (
  .v4642b6(w34),
  .v6dda25(w46)
 );
 vf72b3a vf9987a (
  .vc93bbe(w33),
  .v381ebf(w34),
  .vb186da(w35),
  .v50d6c6(w54)
 );
 v21cfcc v3d53f8 (
  .v9fb85f(w35)
 );
endmodule

/*-------------------------------------------------*/
/*--   */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- 
/*-------------------------------------------------*/
//---- Top entity
module v89d234 #(
 parameter v422d28 = 0
) (
 input v41eb95,
 input [7:0] v39f831,
 input vf892a0,
 output [7:0] vb1c024
);
 localparam p0 = v422d28;
 wire [0:7] w1;
 wire [0:7] w2;
 wire w3;
 wire w4;
 assign vb1c024 = w1;
 assign w2 = v39f831;
 assign w3 = vf892a0;
 assign w4 = v41eb95;
 v89d234_v9148cb #(
  .INI(p0)
 ) v9148cb (
  .q(w1),
  .d(w2),
  .load(w3),
  .clk(w4)
 );
endmodule

/*-------------------------------------------------*/
/*-- Registro  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Registro de 8 bits
/*-------------------------------------------------*/

module v89d234_v9148cb #(
 parameter INI = 0
) (
 input clk,
 input [7:0] d,
 input load,
 output [7:0] q
);
 localparam N = 8;
 
 reg [N-1:0] q = INI;
 
 always @(posedge clk)
   if (load)
     q <= d;
endmodule
//---- Top entity
module v53847c #(
 parameter vc96e81 = 0
) (
 input v4a6801,
 input v3ba3e6,
 input [7:0] v67ccbf,
 input v9bfaa9,
 input v7d29fb,
 output v0d3330,
 output [7:0] vd50ef8
);
 localparam p0 = vc96e81;
 wire [0:7] w1;
 wire w2;
 wire w3;
 wire [0:7] w4;
 wire w5;
 wire w6;
 wire w7;
 assign vd50ef8 = w1;
 assign w2 = v4a6801;
 assign w3 = v3ba3e6;
 assign w4 = v67ccbf;
 assign w5 = v7d29fb;
 assign w6 = v9bfaa9;
 assign v0d3330 = w7;
 v53847c_v768248 #(
  .INI(p0)
 ) v768248 (
  .q(w1),
  .clk(w2),
  .si(w3),
  .d(w4),
  .shift(w5),
  .load(w6),
  .so(w7)
 );
endmodule

/*-------------------------------------------------*/
/*-- Registro-desplazamiento  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Registro de desplazamiento (izquierda) de 8 bits
/*-------------------------------------------------*/

module v53847c_v768248 #(
 parameter INI = 0
) (
 input clk,
 input si,
 input [7:0] d,
 input load,
 input shift,
 output so,
 output [7:0] q
);
 //-- Numero de bits el registros de desplazamiento
 localparam N = 8;
 
 reg [N-1:0] q = INI;
 
 always @(posedge clk)
   if (load)
     q <= d;
   else if (shift)
     q <= {q[N-2:0], si};
     
 //-- Sacar el bit de mayor peso por serial-out    
 assign so = q[N-1];
endmodule
//---- Top entity
module vdc93d6 (
 input v717e81,
 input ve7f5e6,
 output v3c12b5
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 assign w0 = ve7f5e6;
 assign v3c12b5 = w2;
 assign w3 = v717e81;
 assign w4 = v717e81;
 assign w4 = w3;
 v053dc2 vbb75a1 (
  .vf54559(w0),
  .ve8318d(w1),
  .va4102a(w4)
 );
 v053dc2 vf6c433 (
  .vf54559(w1),
  .ve8318d(w2),
  .va4102a(w3)
 );
endmodule

/*-------------------------------------------------*/
/*-- Sync-x01  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Sync 1-bit input with the system clock domain
/*-------------------------------------------------*/
//---- Top entity
module v053dc2 #(
 parameter v71e305 = 0
) (
 input va4102a,
 input vf54559,
 output ve8318d
);
 localparam p2 = v71e305;
 wire w0;
 wire w1;
 wire w3;
 assign w0 = va4102a;
 assign ve8318d = w1;
 assign w3 = vf54559;
 v053dc2_vb8adf8 #(
  .INI(p2)
 ) vb8adf8 (
  .clk(w0),
  .q(w1),
  .d(w3)
 );
endmodule

/*-------------------------------------------------*/
/*-- DFF  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- D Flip-flop (verilog implementation)
/*-------------------------------------------------*/

module v053dc2_vb8adf8 #(
 parameter INI = 0
) (
 input clk,
 input d,
 output q
);
 //-- Initial value
 reg q = INI;
 
 //-- Capture the input data  
 //-- on the rising edge of  
 //-- the system clock
 always @(posedge clk)
   q <= d;
endmodule
//---- Top entity
module v31e84e (
 input ved8395,
 input ve78ab8,
 output v3487af
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire w5;
 assign w0 = ve78ab8;
 assign w1 = ved8395;
 assign w4 = ve78ab8;
 assign v3487af = w5;
 assign w4 = w0;
 v053dc2 v1bde40 (
  .vf54559(w0),
  .va4102a(w1),
  .ve8318d(w2)
 );
 v3676a0 v9d4cda (
  .v0e28cb(w2),
  .vcbab45(w3)
 );
 vba518e v57aa83 (
  .v0e28cb(w3),
  .v3ca442(w4),
  .vcbab45(w5)
 );
endmodule

/*-------------------------------------------------*/
/*-- Rising-edge-detector  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Rising-edge detector. It generates a 1-period pulse (tic) when a rising edge is detected on the input
/*-------------------------------------------------*/
//---- Top entity
module v3676a0 (
 input v0e28cb,
 output vcbab45
);
 wire w0;
 wire w1;
 assign w0 = v0e28cb;
 assign vcbab45 = w1;
 v3676a0_vd54ca1 vd54ca1 (
  .a(w0),
  .q(w1)
 );
endmodule

/*-------------------------------------------------*/
/*-- NOT  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- NOT gate (Verilog implementation)
/*-------------------------------------------------*/

module v3676a0_vd54ca1 (
 input a,
 output q
);
 //-- NOT Gate
 assign q = ~a;
 
 
endmodule
//---- Top entity
module vba518e (
 input v0e28cb,
 input v3ca442,
 output vcbab45
);
 wire w0;
 wire w1;
 wire w2;
 assign w0 = v0e28cb;
 assign w1 = v3ca442;
 assign vcbab45 = w2;
 vba518e_vf4938a vf4938a (
  .a(w0),
  .b(w1),
  .c(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- AND2  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Two bits input And gate
/*-------------------------------------------------*/

module vba518e_vf4938a (
 input a,
 input b,
 output c
);
 //-- AND gate
 //-- Verilog implementation
 
 assign c = a & b;
 
endmodule
//---- Top entity
module vbc6704 (
 input [7:0] v595263,
 output vc85478,
 output v7ada3f,
 output v2c9812,
 output ve0c1b4,
 output v7c37b3,
 output v8f149e,
 output vb85197,
 output v45ab8c
);
 wire [0:7] w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire w5;
 wire w6;
 wire w7;
 wire w8;
 assign w0 = v595263;
 assign vc85478 = w1;
 assign v7ada3f = w2;
 assign v2c9812 = w3;
 assign ve0c1b4 = w4;
 assign v7c37b3 = w5;
 assign v8f149e = w6;
 assign vb85197 = w7;
 assign v45ab8c = w8;
 vbc6704_v9a2a06 v9a2a06 (
  .i(w0),
  .o7(w1),
  .o6(w2),
  .o5(w3),
  .o4(w4),
  .o3(w5),
  .o2(w6),
  .o1(w7),
  .o0(w8)
 );
endmodule

/*-------------------------------------------------*/
/*-- Separador-bus  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Separador de bus de 8-bits en 8 cables
/*-------------------------------------------------*/

module vbc6704_v9a2a06 (
 input [7:0] i,
 output o7,
 output o6,
 output o5,
 output o4,
 output o3,
 output o2,
 output o1,
 output o0
);
 assign o7 = i[7];
 assign o6 = i[6];
 assign o5 = i[5];
 assign o4 = i[4];
 assign o3 = i[3];
 assign o2 = i[2];
 assign o1 = i[1];
 assign o0 = i[0];
endmodule
//---- Top entity
module vb2090f (
 input v0e28cb,
 input v3ca442,
 output vcbab45
);
 wire w0;
 wire w1;
 wire w2;
 assign w0 = v0e28cb;
 assign w1 = v3ca442;
 assign vcbab45 = w2;
 vb2090f_vf4938a vf4938a (
  .a(w0),
  .b(w1),
  .c(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- AND  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Puerta AND
/*-------------------------------------------------*/

module vb2090f_vf4938a (
 input a,
 input b,
 output c
);
 //-- Puerta AND
 
 //-- module and (input wire a, input wire b,
 //--             output wire c);
 
 assign c = a & b;
 
 //-- endmodule
endmodule
//---- Top entity
module v35f267 (
 input v0e28cb,
 output vcbab45
);
 wire w0;
 wire w1;
 assign w0 = v0e28cb;
 assign vcbab45 = w1;
 v35f267_vd54ca1 vd54ca1 (
  .a(w0),
  .c(w1)
 );
endmodule

/*-------------------------------------------------*/
/*-- NOT  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Puerta NOT
/*-------------------------------------------------*/

module v35f267_vd54ca1 (
 input a,
 output c
);
 //-- Puerta NOT
 
 //-- module (input wire a, output wire c);
 
 
 assign c = ~a;
 
 
 //-- endmodule
 
endmodule
//---- Top entity
module v45c913 (
 input [3:0] v930b03,
 output v5b73e8,
 output vc90115,
 output v2812a7,
 output v593f43
);
 wire [0:3] w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 assign w0 = v930b03;
 assign v2812a7 = w1;
 assign v593f43 = w2;
 assign vc90115 = w3;
 assign v5b73e8 = w4;
 v45c913_v9a2a06 v9a2a06 (
  .i(w0),
  .o1(w1),
  .o0(w2),
  .o2(w3),
  .o3(w4)
 );
endmodule

/*-------------------------------------------------*/
/*-- Separador-bus  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Separador de bus de 4-bits en 4 cables
/*-------------------------------------------------*/

module v45c913_v9a2a06 (
 input [3:0] i,
 output o3,
 output o2,
 output o1,
 output o0
);
 assign o3 = i[3];
 assign o2 = i[2];
 assign o1 = i[1];
 assign o0 = i[0];
endmodule
//---- Top entity
module vd8f675 (
 input v77b6c4,
 input v1311d2,
 input vee8a83,
 input v03aaf0,
 output [3:0] v5d9ba2
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire [0:3] w4;
 assign w0 = vee8a83;
 assign w1 = v03aaf0;
 assign w2 = v1311d2;
 assign w3 = v77b6c4;
 assign v5d9ba2 = w4;
 vd8f675_v9a2a06 v9a2a06 (
  .i1(w0),
  .i0(w1),
  .i2(w2),
  .i3(w3),
  .o(w4)
 );
endmodule

/*-------------------------------------------------*/
/*-- Agregador-bus  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Agregador de 4 cables en un bus de 4-bits
/*-------------------------------------------------*/

module vd8f675_v9a2a06 (
 input i3,
 input i2,
 input i1,
 input i0,
 output [3:0] o
);
 assign o = {i3,i2, i1, i0};
 
endmodule
//---- Top entity
module v766f27 #(
 parameter vb36a78 = "vb36a78.list"
) (
 input [3:0] v851180,
 output [3:0] vfde47f
);
 localparam p0 = vb36a78;
 wire [0:3] w1;
 wire [0:3] w2;
 assign w1 = v851180;
 assign vfde47f = w2;
 v766f27_v361fe9 #(
  .DATA(p0)
 ) v361fe9 (
  .i(w1),
  .q(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- mi-tabla4-4  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Circuito combinacional de 4 entradas y 4 salidas
/*-------------------------------------------------*/

module v766f27_v361fe9 #(
 parameter DATA = 0
) (
 input [3:0] i,
 output [3:0] q
);
 
 //-- Bits del bus de entrada
 localparam N = 4;
 
 //-- Bits del bus de salida
 localparam M = 4;
 
 //-- Calcular tamaño de la tabla
 //-- (filas) segun los bits de entrada
 localparam TAM = 2 ** N;
 
 //-- Definición de la tabla
 //-- Tabla de TAM elementos de M bits
 reg [M-1:0] tabla[0:TAM-1];
 
 //-- Read the table
 assign q = tabla[i];
 
 //-- Init table from DATA parameters
 initial begin
   if (DATA) $readmemb(DATA, tabla);
 end
endmodule
//---- Top entity
module vbce541 #(
 parameter va04f5d = 16777216
) (
 input v6dda25,
 output v4642b6
);
 localparam p1 = va04f5d;
 wire w0;
 wire [0:23] w2;
 wire [0:23] w3;
 wire w4;
 wire w5;
 assign v4642b6 = w0;
 assign w5 = v6dda25;
 assign w4 = w0;
 vef98b5 #(
  .vc5c8ea(p1)
 ) v4016e8 (
  .ve70c2d(w3)
 );
 vd84ae0 v45b714 (
  .v4642b6(w0),
  .va89056(w2),
  .v06bdfb(w3)
 );
 v97d607 v2299cf (
  .v9e1c43(w2),
  .ve556f1(w4),
  .v6dda25(w5)
 );
endmodule

/*-------------------------------------------------*/
/*-- sysclk_divN_24  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- sysclk_divN_24bits: Generate a signal from the division of the system clock by N. (24-bits precision) (N = 2,3,4,..,0x1000000))
/*-------------------------------------------------*/
//---- Top entity
module vef98b5 #(
 parameter vc5c8ea = 1
) (
 output [23:0] ve70c2d
);
 localparam p0 = vc5c8ea;
 wire [0:23] w1;
 assign ve70c2d = w1;
 vef98b5_v465065 #(
  .VALUE(p0)
 ) v465065 (
  .k(w1)
 );
endmodule

/*-------------------------------------------------*/
/*-- 24-bits-k-1  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Generic: 24-bits k-1 constant (Input values: 1,2,...,h1000000). It returns the value input by the user minus 1. Outputs: 0,1,2,...,FFFFFF
/*-------------------------------------------------*/

module vef98b5_v465065 #(
 parameter VALUE = 0
) (
 output [23:0] k
);
 assign k = VALUE-1;
endmodule
//---- Top entity
module vd84ae0 (
 input [23:0] v06bdfb,
 input [23:0] va89056,
 output v4642b6
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire [0:23] w4;
 wire [0:23] w5;
 wire [0:7] w6;
 wire [0:7] w7;
 wire [0:7] w8;
 wire [0:7] w9;
 wire [0:7] w10;
 wire [0:7] w11;
 assign v4642b6 = w0;
 assign w4 = v06bdfb;
 assign w5 = va89056;
 vb2762a vb6832a (
  .v4642b6(w1),
  .v715730(w8),
  .vf191e6(w11)
 );
 vb2762a v302658 (
  .v4642b6(w2),
  .v715730(w7),
  .vf191e6(w10)
 );
 vae245c v9196c7 (
  .vcbab45(w0),
  .v3ca442(w1),
  .v0e28cb(w2),
  .v033bf6(w3)
 );
 v6fef69 vb1e577 (
  .v9804b7(w5),
  .vd83cb2(w9),
  .v243fb2(w10),
  .va2a3a1(w11)
 );
 v6fef69 v62b64f (
  .v9804b7(w4),
  .vd83cb2(w6),
  .v243fb2(w7),
  .va2a3a1(w8)
 );
 vb2762a v9a65c6 (
  .v4642b6(w3),
  .v715730(w6),
  .vf191e6(w9)
 );
endmodule

/*-------------------------------------------------*/
/*-- comp2-24bits  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Comp2-24bit: Comparator of two 24-bit numbers
/*-------------------------------------------------*/
//---- Top entity
module vb2762a (
 input [7:0] v715730,
 input [7:0] vf191e6,
 output v4642b6
);
 wire w0;
 wire w1;
 wire w2;
 wire [0:7] w3;
 wire [0:7] w4;
 wire [0:3] w5;
 wire [0:3] w6;
 wire [0:3] w7;
 wire [0:3] w8;
 assign v4642b6 = w0;
 assign w3 = v715730;
 assign w4 = vf191e6;
 v438230 v577a36 (
  .v4642b6(w2),
  .v693354(w6),
  .v5369cd(w8)
 );
 vba518e v707c6e (
  .vcbab45(w0),
  .v0e28cb(w1),
  .v3ca442(w2)
 );
 v6bdcd9 v921a9f (
  .vcc8c7c(w4),
  .v651522(w7),
  .v2cc41f(w8)
 );
 v6bdcd9 v8cfa4d (
  .vcc8c7c(w3),
  .v651522(w5),
  .v2cc41f(w6)
 );
 v438230 vfc1765 (
  .v4642b6(w1),
  .v693354(w5),
  .v5369cd(w7)
 );
endmodule

/*-------------------------------------------------*/
/*-- comp2-8bits  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Comp2-8bit: Comparator of two 8-bit numbers
/*-------------------------------------------------*/
//---- Top entity
module v438230 (
 input [3:0] v693354,
 input [3:0] v5369cd,
 output v4642b6
);
 wire w0;
 wire [0:3] w1;
 wire [0:3] w2;
 wire w3;
 wire w4;
 wire w5;
 wire w6;
 wire w7;
 wire w8;
 wire w9;
 wire w10;
 wire w11;
 wire w12;
 wire w13;
 wire w14;
 assign v4642b6 = w0;
 assign w1 = v693354;
 assign w2 = v5369cd;
 v23b15b v09a5a5 (
  .v4642b6(w3),
  .v27dec4(w12),
  .v6848e9(w14)
 );
 v23b15b vc1b29d (
  .v4642b6(w4),
  .v27dec4(w11),
  .v6848e9(w13)
 );
 v23b15b vcd27ce (
  .v4642b6(w5),
  .v27dec4(w9),
  .v6848e9(w10)
 );
 vc4f23a vea9c80 (
  .v985fcb(w1),
  .v4f1fd3(w7),
  .vda577d(w9),
  .v3f8943(w11),
  .v64d863(w12)
 );
 vc4f23a va7dcdc (
  .v985fcb(w2),
  .v4f1fd3(w8),
  .vda577d(w10),
  .v3f8943(w13),
  .v64d863(w14)
 );
 v23b15b va0849c (
  .v4642b6(w6),
  .v27dec4(w7),
  .v6848e9(w8)
 );
 veffd42 v6e3e65 (
  .vcbab45(w0),
  .v3ca442(w3),
  .v0e28cb(w4),
  .v033bf6(w5),
  .v9eb652(w6)
 );
endmodule

/*-------------------------------------------------*/
/*-- comp2-4bits  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Comp2-4bit: Comparator of two 4-bit numbers
/*-------------------------------------------------*/
//---- Top entity
module v23b15b (
 input v27dec4,
 input v6848e9,
 output v4642b6
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 assign w1 = v27dec4;
 assign v4642b6 = w2;
 assign w3 = v6848e9;
 vd12401 v955b2b (
  .vcbab45(w0),
  .v0e28cb(w1),
  .v3ca442(w3)
 );
 v3676a0 vf92936 (
  .v0e28cb(w0),
  .vcbab45(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- comp2-1bit  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Comp2-1bit: Comparator of two 1-bit numbers
/*-------------------------------------------------*/
//---- Top entity
module vd12401 (
 input v0e28cb,
 input v3ca442,
 output vcbab45
);
 wire w0;
 wire w1;
 wire w2;
 assign w0 = v0e28cb;
 assign w1 = v3ca442;
 assign vcbab45 = w2;
 vd12401_vf4938a vf4938a (
  .a(w0),
  .b(w1),
  .c(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- XOR2  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- XOR gate: two bits input xor gate
/*-------------------------------------------------*/

module vd12401_vf4938a (
 input a,
 input b,
 output c
);
 //-- XOR gate
 //-- Verilog implementation
 
 assign c = a ^ b;
 
endmodule
//---- Top entity
module vc4f23a (
 input [3:0] v985fcb,
 output v4f1fd3,
 output vda577d,
 output v3f8943,
 output v64d863
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire [0:3] w4;
 assign v3f8943 = w0;
 assign v64d863 = w1;
 assign vda577d = w2;
 assign v4f1fd3 = w3;
 assign w4 = v985fcb;
 vc4f23a_v9a2a06 v9a2a06 (
  .o1(w0),
  .o0(w1),
  .o2(w2),
  .o3(w3),
  .i(w4)
 );
endmodule

/*-------------------------------------------------*/
/*-- Bus4-Split-all  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Bus4-Split-all: Split the 4-bits bus into its wires
/*-------------------------------------------------*/

module vc4f23a_v9a2a06 (
 input [3:0] i,
 output o3,
 output o2,
 output o1,
 output o0
);
 assign o3 = i[3];
 assign o2 = i[2];
 assign o1 = i[1];
 assign o0 = i[0];
endmodule
//---- Top entity
module veffd42 (
 input v9eb652,
 input v033bf6,
 input v0e28cb,
 input v3ca442,
 output vcbab45
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire w5;
 wire w6;
 assign w0 = v3ca442;
 assign w1 = v9eb652;
 assign w2 = v033bf6;
 assign w3 = v0e28cb;
 assign vcbab45 = w4;
 vba518e vf3ef0f (
  .v3ca442(w0),
  .v0e28cb(w3),
  .vcbab45(w6)
 );
 vba518e vdcc53d (
  .v0e28cb(w1),
  .v3ca442(w2),
  .vcbab45(w5)
 );
 vba518e v17ac22 (
  .vcbab45(w4),
  .v0e28cb(w5),
  .v3ca442(w6)
 );
endmodule

/*-------------------------------------------------*/
/*-- AND4  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Three bits input And gate
/*-------------------------------------------------*/
//---- Top entity
module v6bdcd9 (
 input [7:0] vcc8c7c,
 output [3:0] v651522,
 output [3:0] v2cc41f
);
 wire [0:3] w0;
 wire [0:3] w1;
 wire [0:7] w2;
 assign v651522 = w0;
 assign v2cc41f = w1;
 assign w2 = vcc8c7c;
 v6bdcd9_v9a2a06 v9a2a06 (
  .o1(w0),
  .o0(w1),
  .i(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- Bus8-Split-half  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Bus8-Split-half: Split the 8-bits bus into two buses of the same size
/*-------------------------------------------------*/

module v6bdcd9_v9a2a06 (
 input [7:0] i,
 output [3:0] o1,
 output [3:0] o0
);
 assign o1 = i[7:4];
 assign o0 = i[3:0];
endmodule
//---- Top entity
module vae245c (
 input v033bf6,
 input v0e28cb,
 input v3ca442,
 output vcbab45
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 assign w0 = v033bf6;
 assign w1 = v0e28cb;
 assign w2 = v3ca442;
 assign vcbab45 = w4;
 vba518e v19b5b0 (
  .v0e28cb(w0),
  .v3ca442(w1),
  .vcbab45(w3)
 );
 vba518e vf3ef0f (
  .v3ca442(w2),
  .v0e28cb(w3),
  .vcbab45(w4)
 );
endmodule

/*-------------------------------------------------*/
/*-- AND3  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Three bits input And gate
/*-------------------------------------------------*/
//---- Top entity
module v6fef69 (
 input [23:0] v9804b7,
 output [7:0] vd83cb2,
 output [7:0] v243fb2,
 output [7:0] va2a3a1
);
 wire [0:7] w0;
 wire [0:7] w1;
 wire [0:7] w2;
 wire [0:23] w3;
 assign v243fb2 = w0;
 assign vd83cb2 = w1;
 assign va2a3a1 = w2;
 assign w3 = v9804b7;
 v6fef69_v9a2a06 v9a2a06 (
  .o1(w0),
  .o2(w1),
  .o0(w2),
  .i(w3)
 );
endmodule

/*-------------------------------------------------*/
/*-- Bus24-Split-one-third  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Bus24-Split-one-third: Split the 24-bits bus into three buses of  the same size
/*-------------------------------------------------*/

module v6fef69_v9a2a06 (
 input [23:0] i,
 output [7:0] o2,
 output [7:0] o1,
 output [7:0] o0
);
 assign o2 = i[23:16];
 assign o1 = i[15:8];
 assign o0 = i[7:0];
endmodule
//---- Top entity
module v97d607 (
 input v6dda25,
 input ve556f1,
 output [23:0] v9e1c43,
 output ve37344
);
 wire w0;
 wire [0:23] w1;
 wire [0:23] w2;
 wire w3;
 wire [0:23] w4;
 wire w5;
 assign w0 = ve556f1;
 assign w3 = v6dda25;
 assign v9e1c43 = w4;
 assign ve37344 = w5;
 assign w4 = w1;
 v5495b5 v5e4c9c (
  .v782748(w0),
  .vb02eea(w1),
  .v15c6e6(w2),
  .v6dda25(w3)
 );
 v9c4559 v62e821 (
  .v005b83(w1),
  .v53d485(w2),
  .v4642b6(w5)
 );
endmodule

/*-------------------------------------------------*/
/*-- syscounter-rst-24bits  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- 24-bits Syscounter with reset
/*-------------------------------------------------*/
//---- Top entity
module v5495b5 (
 input v6dda25,
 input v782748,
 input [23:0] v15c6e6,
 output [23:0] vb02eea
);
 wire [0:23] w0;
 wire [0:23] w1;
 wire [0:7] w2;
 wire [0:7] w3;
 wire [0:7] w4;
 wire [0:7] w5;
 wire [0:7] w6;
 wire [0:7] w7;
 wire w8;
 wire w9;
 wire w10;
 wire w11;
 wire w12;
 wire w13;
 assign vb02eea = w0;
 assign w1 = v15c6e6;
 assign w8 = v6dda25;
 assign w9 = v6dda25;
 assign w10 = v6dda25;
 assign w11 = v782748;
 assign w12 = v782748;
 assign w13 = v782748;
 assign w9 = w8;
 assign w10 = w8;
 assign w10 = w9;
 assign w12 = w11;
 assign w13 = w11;
 assign w13 = w12;
 v6fef69 vad6f1d (
  .v9804b7(w1),
  .va2a3a1(w5),
  .v243fb2(w6),
  .vd83cb2(w7)
 );
 v33e50d vba7365 (
  .v6d326e(w0),
  .v77c6e9(w2),
  .vf7d213(w3),
  .vba04ee(w4)
 );
 vcf4344 v13ddeb (
  .vc1f0d2(w2),
  .vd85d4e(w5),
  .v6dda25(w10),
  .v782748(w13)
 );
 vcf4344 v08e1bd (
  .vc1f0d2(w3),
  .vd85d4e(w6),
  .v6dda25(w9),
  .v782748(w12)
 );
 vcf4344 v5c3b0f (
  .vc1f0d2(w4),
  .vd85d4e(w7),
  .v6dda25(w8),
  .v782748(w11)
 );
endmodule

/*-------------------------------------------------*/
/*-- DFF-rst-x24  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- DFF-rst-x24: 24 D flip-flops in paralell with reset
/*-------------------------------------------------*/
//---- Top entity
module v33e50d (
 input [7:0] vba04ee,
 input [7:0] vf7d213,
 input [7:0] v77c6e9,
 output [23:0] v6d326e
);
 wire [0:23] w0;
 wire [0:7] w1;
 wire [0:7] w2;
 wire [0:7] w3;
 assign v6d326e = w0;
 assign w1 = vf7d213;
 assign w2 = v77c6e9;
 assign w3 = vba04ee;
 v33e50d_v9a2a06 v9a2a06 (
  .o(w0),
  .i1(w1),
  .i0(w2),
  .i2(w3)
 );
endmodule

/*-------------------------------------------------*/
/*-- Bus24-Join-one-third  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Bus24-Join-one-third: Join the three buses into an 24-bits Bus
/*-------------------------------------------------*/

module v33e50d_v9a2a06 (
 input [7:0] i2,
 input [7:0] i1,
 input [7:0] i0,
 output [23:0] o
);
 assign o = {i2, i1, i0};
 
endmodule
//---- Top entity
module vcf4344 (
 input v6dda25,
 input v782748,
 input [7:0] vd85d4e,
 output [7:0] vc1f0d2
);
 wire [0:3] w0;
 wire [0:3] w1;
 wire [0:7] w2;
 wire [0:7] w3;
 wire [0:3] w4;
 wire [0:3] w5;
 wire w6;
 wire w7;
 wire w8;
 wire w9;
 assign w2 = vd85d4e;
 assign vc1f0d2 = w3;
 assign w6 = v6dda25;
 assign w7 = v6dda25;
 assign w8 = v782748;
 assign w9 = v782748;
 assign w7 = w6;
 assign w9 = w8;
 v5c75f6 vbdef88 (
  .v50034e(w0),
  .v4de61b(w1),
  .v6dda25(w7),
  .v782748(w9)
 );
 v6bdcd9 vc95779 (
  .v2cc41f(w1),
  .vcc8c7c(w2),
  .v651522(w4)
 );
 vafb28f v618315 (
  .v3c88fc(w0),
  .va9ac17(w3),
  .v515fe7(w5)
 );
 v5c75f6 v6188f9 (
  .v4de61b(w4),
  .v50034e(w5),
  .v6dda25(w6),
  .v782748(w8)
 );
endmodule

/*-------------------------------------------------*/
/*-- DFF-rst-x08  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- DFF-rst-x08: Eight D flip-flops in paralell with reset
/*-------------------------------------------------*/
//---- Top entity
module v5c75f6 (
 input v6dda25,
 input v782748,
 input [3:0] v4de61b,
 output [3:0] v50034e
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire w5;
 wire [0:3] w6;
 wire [0:3] w7;
 wire w8;
 wire w9;
 wire w10;
 wire w11;
 wire w12;
 wire w13;
 wire w14;
 wire w15;
 wire w16;
 wire w17;
 assign w6 = v4de61b;
 assign v50034e = w7;
 assign w10 = v6dda25;
 assign w11 = v6dda25;
 assign w12 = v6dda25;
 assign w13 = v6dda25;
 assign w14 = v782748;
 assign w15 = v782748;
 assign w16 = v782748;
 assign w17 = v782748;
 assign w11 = w10;
 assign w12 = w10;
 assign w12 = w11;
 assign w13 = w10;
 assign w13 = w11;
 assign w13 = w12;
 assign w15 = w14;
 assign w16 = w14;
 assign w16 = w15;
 assign w17 = w14;
 assign w17 = w15;
 assign w17 = w16;
 vc4f23a v4b1225 (
  .v3f8943(w2),
  .v64d863(w3),
  .vda577d(w4),
  .v985fcb(w6),
  .v4f1fd3(w8)
 );
 v84f0a1 v6491fd (
  .v03aaf0(w0),
  .vee8a83(w1),
  .vf8041d(w5),
  .v11bca5(w7),
  .vd84a57(w9)
 );
 v2be0f8 v10a04f (
  .v4642b6(w0),
  .vf354ee(w3),
  .vd53b77(w13),
  .v27dec4(w17)
 );
 v2be0f8 v7d9648 (
  .v4642b6(w1),
  .vf354ee(w2),
  .vd53b77(w12),
  .v27dec4(w16)
 );
 v2be0f8 v004b14 (
  .vf354ee(w4),
  .v4642b6(w5),
  .vd53b77(w11),
  .v27dec4(w15)
 );
 v2be0f8 v8aa818 (
  .vf354ee(w8),
  .v4642b6(w9),
  .vd53b77(w10),
  .v27dec4(w14)
 );
endmodule

/*-------------------------------------------------*/
/*-- DFF-rst-x04  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- DFF-rst-x04: Three D flip-flops in paralell with reset
/*-------------------------------------------------*/
//---- Top entity
module v84f0a1 (
 input vd84a57,
 input vf8041d,
 input vee8a83,
 input v03aaf0,
 output [3:0] v11bca5
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire [0:3] w4;
 assign w0 = vee8a83;
 assign w1 = v03aaf0;
 assign w2 = vf8041d;
 assign w3 = vd84a57;
 assign v11bca5 = w4;
 v84f0a1_v9a2a06 v9a2a06 (
  .i1(w0),
  .i0(w1),
  .i2(w2),
  .i3(w3),
  .o(w4)
 );
endmodule

/*-------------------------------------------------*/
/*-- Bus4-Join-all  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Bus4-Join-all: Join all the wires into a 4-bits Bus
/*-------------------------------------------------*/

module v84f0a1_v9a2a06 (
 input i3,
 input i2,
 input i1,
 input i0,
 output [3:0] o
);
 assign o = {i3, i2, i1, i0};
 
endmodule
//---- Top entity
module v2be0f8 #(
 parameter vbd3217 = 0
) (
 input vd53b77,
 input v27dec4,
 input vf354ee,
 output v4642b6
);
 localparam p5 = vbd3217;
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire w6;
 assign w2 = v27dec4;
 assign w3 = vf354ee;
 assign v4642b6 = w4;
 assign w6 = vd53b77;
 v3676a0 v7539bf (
  .vcbab45(w1),
  .v0e28cb(w2)
 );
 vba518e vfe8158 (
  .vcbab45(w0),
  .v0e28cb(w1),
  .v3ca442(w3)
 );
 v053dc2 #(
  .v71e305(p5)
 ) vd104a4 (
  .vf54559(w0),
  .ve8318d(w4),
  .va4102a(w6)
 );
endmodule

/*-------------------------------------------------*/
/*-- DFF-rst-x01  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- DFF-rst-x01: D Flip flop with reset input. When rst=1, the DFF is 0
/*-------------------------------------------------*/
//---- Top entity
module vafb28f (
 input [3:0] v515fe7,
 input [3:0] v3c88fc,
 output [7:0] va9ac17
);
 wire [0:7] w0;
 wire [0:3] w1;
 wire [0:3] w2;
 assign va9ac17 = w0;
 assign w1 = v515fe7;
 assign w2 = v3c88fc;
 vafb28f_v9a2a06 v9a2a06 (
  .o(w0),
  .i1(w1),
  .i0(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- Bus8-Join-half  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Bus8-Join-half: Join the two same halves into an 8-bits Bus
/*-------------------------------------------------*/

module vafb28f_v9a2a06 (
 input [3:0] i1,
 input [3:0] i0,
 output [7:0] o
);
 assign o = {i1, i0};
 
endmodule
//---- Top entity
module v9c4559 #(
 parameter v6c5139 = 1
) (
 input [23:0] v005b83,
 output v4642b6,
 output [23:0] v53d485
);
 localparam p1 = v6c5139;
 wire w0;
 wire [0:23] w2;
 wire [0:23] w3;
 assign v4642b6 = w0;
 assign w2 = v005b83;
 assign v53d485 = w3;
 v44c099 #(
  .vd73390(p1)
 ) v8c0045 (
  .v4642b6(w0),
  .vd90f46(w2),
  .v8826c0(w3)
 );
endmodule

/*-------------------------------------------------*/
/*-- Inc1-24bits  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Inc1-24bit: Increment a 24-bits number by one
/*-------------------------------------------------*/
//---- Top entity
module v44c099 #(
 parameter vd73390 = 0
) (
 input [23:0] vd90f46,
 output v4642b6,
 output [23:0] v8826c0
);
 localparam p1 = vd73390;
 wire w0;
 wire [0:23] w2;
 wire [0:23] w3;
 wire [0:23] w4;
 assign v4642b6 = w0;
 assign v8826c0 = w2;
 assign w3 = vd90f46;
 v4c802f #(
  .vc5c8ea(p1)
 ) ve78914 (
  .v8513f7(w4)
 );
 v91404d v19ed8b (
  .v4642b6(w0),
  .vb5c06c(w2),
  .v7959e8(w3),
  .vb5a2f2(w4)
 );
endmodule

/*-------------------------------------------------*/
/*-- AdderK-24bits  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- AdderK-24bit: Adder of 24-bit operand and 24-bit constant
/*-------------------------------------------------*/
//---- Top entity
module v4c802f #(
 parameter vc5c8ea = 0
) (
 output [23:0] v8513f7
);
 localparam p0 = vc5c8ea;
 wire [0:23] w1;
 assign v8513f7 = w1;
 v4c802f_v465065 #(
  .VALUE(p0)
 ) v465065 (
  .k(w1)
 );
endmodule

/*-------------------------------------------------*/
/*-- 24-bits-gen-constant  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Generic: 24-bits generic constant
/*-------------------------------------------------*/

module v4c802f_v465065 #(
 parameter VALUE = 0
) (
 output [23:0] k
);
 assign k = VALUE;
endmodule
//---- Top entity
module v91404d (
 input [23:0] vb5a2f2,
 input [23:0] v7959e8,
 output v4642b6,
 output [23:0] vb5c06c
);
 wire w0;
 wire [0:7] w1;
 wire [0:7] w2;
 wire w3;
 wire w4;
 wire [0:15] w5;
 wire [0:23] w6;
 wire [0:15] w7;
 wire [0:23] w8;
 wire [0:15] w9;
 wire [0:7] w10;
 wire [0:23] w11;
 wire [0:7] w12;
 wire [0:7] w13;
 wire [0:7] w14;
 wire [0:7] w15;
 wire [0:7] w16;
 wire [0:7] w17;
 assign v4642b6 = w4;
 assign w6 = v7959e8;
 assign w8 = vb5a2f2;
 assign vb5c06c = w11;
 vcb23aa v8e0bba (
  .v4642b6(w0),
  .v62bf25(w2),
  .v39966a(w16),
  .veb2f59(w17)
 );
 vc3c498 v917bbf (
  .vb9cfc3(w0),
  .veeaa8e(w1),
  .v4642b6(w3),
  .v45c6ee(w14),
  .v20212e(w15)
 );
 v8cc49c v03c3e3 (
  .vb334ae(w1),
  .v2b8a97(w2),
  .v14a530(w5)
 );
 vab13f0 v43653c (
  .vb18564(w6),
  .vf0a06e(w7),
  .v5246f6(w17)
 );
 v306ca3 v177126 (
  .v91b9c1(w7),
  .vef5eee(w13),
  .vd3ef3b(w15)
 );
 vab13f0 vf15711 (
  .vb18564(w8),
  .vf0a06e(w9),
  .v5246f6(w16)
 );
 v306ca3 vf9ed57 (
  .v91b9c1(w9),
  .vef5eee(w12),
  .vd3ef3b(w14)
 );
 vc3c498 vf0db78 (
  .vb9cfc3(w3),
  .v4642b6(w4),
  .veeaa8e(w10),
  .v45c6ee(w12),
  .v20212e(w13)
 );
 va52e3b v67022b (
  .vbf8961(w5),
  .vf7d213(w10),
  .v6d326e(w11)
 );
endmodule

/*-------------------------------------------------*/
/*-- Adder-24bits  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Adder-24bits: Adder of two operands of 24 bits
/*-------------------------------------------------*/
//---- Top entity
module vcb23aa (
 input [7:0] v39966a,
 input [7:0] veb2f59,
 output v4642b6,
 output [7:0] v62bf25
);
 wire [0:7] w0;
 wire [0:7] w1;
 wire [0:3] w2;
 wire [0:3] w3;
 wire [0:7] w4;
 wire w5;
 wire w6;
 wire [0:3] w7;
 wire [0:3] w8;
 wire [0:3] w9;
 wire [0:3] w10;
 assign w0 = veb2f59;
 assign w1 = v39966a;
 assign v62bf25 = w4;
 assign v4642b6 = w5;
 v6bdcd9 vd88c66 (
  .vcc8c7c(w0),
  .v651522(w9),
  .v2cc41f(w10)
 );
 v6bdcd9 v26a0bb (
  .vcc8c7c(w1),
  .v651522(w7),
  .v2cc41f(w8)
 );
 v25966b v9ea427 (
  .v817794(w3),
  .v4642b6(w6),
  .v0550b6(w8),
  .v24708e(w10)
 );
 vafb28f vc75346 (
  .v515fe7(w2),
  .v3c88fc(w3),
  .va9ac17(w4)
 );
 va1ce30 v40c17f (
  .v817794(w2),
  .v4642b6(w5),
  .vb9cfc3(w6),
  .v0550b6(w7),
  .v24708e(w9)
 );
endmodule

/*-------------------------------------------------*/
/*-- Adder-8bits  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Adder-8bits: Adder of two operands of 8 bits
/*-------------------------------------------------*/
//---- Top entity
module v25966b (
 input [3:0] v0550b6,
 input [3:0] v24708e,
 output v4642b6,
 output [3:0] v817794
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire [0:3] w5;
 wire [0:3] w6;
 wire [0:3] w7;
 wire w8;
 wire w9;
 wire w10;
 wire w11;
 wire w12;
 wire w13;
 wire w14;
 wire w15;
 wire w16;
 wire w17;
 wire w18;
 assign w5 = v24708e;
 assign w6 = v0550b6;
 assign v817794 = w7;
 assign v4642b6 = w9;
 v1ea21d vdbe125 (
  .v4642b6(w0),
  .v8e8a67(w2),
  .v27dec4(w15),
  .v82de4f(w18)
 );
 vad119b vb8ad86 (
  .v0ef266(w0),
  .v8e8a67(w1),
  .v4642b6(w3),
  .v27dec4(w14),
  .v82de4f(w17)
 );
 vad119b v5d29b2 (
  .v0ef266(w3),
  .v8e8a67(w4),
  .v4642b6(w8),
  .v27dec4(w12),
  .v82de4f(w16)
 );
 vc4f23a vf4a6ff (
  .v985fcb(w5),
  .v4f1fd3(w13),
  .vda577d(w16),
  .v3f8943(w17),
  .v64d863(w18)
 );
 vc4f23a v9d4632 (
  .v985fcb(w6),
  .v4f1fd3(w11),
  .vda577d(w12),
  .v3f8943(w14),
  .v64d863(w15)
 );
 v84f0a1 v140dbf (
  .vee8a83(w1),
  .v03aaf0(w2),
  .vf8041d(w4),
  .v11bca5(w7),
  .vd84a57(w10)
 );
 vad119b v5c5937 (
  .v0ef266(w8),
  .v4642b6(w9),
  .v8e8a67(w10),
  .v27dec4(w11),
  .v82de4f(w13)
 );
endmodule

/*-------------------------------------------------*/
/*-- Adder-4bits  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Adder-4bits: Adder of two operands of 4 bits
/*-------------------------------------------------*/
//---- Top entity
module v1ea21d (
 input v27dec4,
 input v82de4f,
 output v4642b6,
 output v8e8a67
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 assign w0 = v82de4f;
 assign w1 = v27dec4;
 assign v4642b6 = w3;
 assign v8e8a67 = w4;
 vad119b vb820a1 (
  .v82de4f(w0),
  .v27dec4(w1),
  .v0ef266(w2),
  .v4642b6(w3),
  .v8e8a67(w4)
 );
 vd30ca9 v23ebb6 (
  .v9fb85f(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- Adder-1bit  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Adder-1bit: Adder of two operands of 1 bit
/*-------------------------------------------------*/
//---- Top entity
module vad119b (
 input v27dec4,
 input v82de4f,
 input v0ef266,
 output v4642b6,
 output v8e8a67
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire w5;
 wire w6;
 wire w7;
 wire w8;
 wire w9;
 wire w10;
 wire w11;
 assign v8e8a67 = w1;
 assign v4642b6 = w5;
 assign w6 = v27dec4;
 assign w7 = v27dec4;
 assign w8 = v82de4f;
 assign w9 = v82de4f;
 assign w10 = v0ef266;
 assign w11 = v0ef266;
 assign w2 = w0;
 assign w7 = w6;
 assign w9 = w8;
 assign w11 = w10;
 vd12401 v2e3d9f (
  .vcbab45(w0),
  .v0e28cb(w7),
  .v3ca442(w9)
 );
 vd12401 vb50462 (
  .v0e28cb(w0),
  .vcbab45(w1),
  .v3ca442(w11)
 );
 vba518e v4882f4 (
  .v3ca442(w2),
  .vcbab45(w3),
  .v0e28cb(w10)
 );
 vba518e v8fcf41 (
  .vcbab45(w4),
  .v0e28cb(w6),
  .v3ca442(w8)
 );
 v873425 vc5b8b9 (
  .v3ca442(w3),
  .v0e28cb(w4),
  .vcbab45(w5)
 );
endmodule

/*-------------------------------------------------*/
/*-- AdderC-1bit  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- AdderC-1bit: Adder of two operands of 1 bit plus the carry in
/*-------------------------------------------------*/
//---- Top entity
module v873425 (
 input v0e28cb,
 input v3ca442,
 output vcbab45
);
 wire w0;
 wire w1;
 wire w2;
 assign w0 = v0e28cb;
 assign w1 = v3ca442;
 assign vcbab45 = w2;
 v873425_vf4938a vf4938a (
  .a(w0),
  .b(w1),
  .c(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- OR2  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- OR2: Two bits input OR gate
/*-------------------------------------------------*/

module v873425_vf4938a (
 input a,
 input b,
 output c
);
 //-- OR Gate
 //-- Verilog implementation
 
 assign c = a | b;
 
 
endmodule
//---- Top entity
module vd30ca9 (
 output v9fb85f
);
 wire w0;
 assign v9fb85f = w0;
 vd30ca9_vb2eccd vb2eccd (
  .q(w0)
 );
endmodule

/*-------------------------------------------------*/
/*-- bit-0  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Constant bit 0
/*-------------------------------------------------*/

module vd30ca9_vb2eccd (
 output q
);
 //-- Constant bit-0
 assign q = 1'b0;
 
 
endmodule
//---- Top entity
module va1ce30 (
 input [3:0] v0550b6,
 input [3:0] v24708e,
 input vb9cfc3,
 output v4642b6,
 output [3:0] v817794
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire [0:3] w5;
 wire [0:3] w6;
 wire [0:3] w7;
 wire w8;
 wire w9;
 wire w10;
 wire w11;
 wire w12;
 wire w13;
 wire w14;
 wire w15;
 wire w16;
 wire w17;
 wire w18;
 wire w19;
 assign w5 = v24708e;
 assign w6 = v0550b6;
 assign v817794 = w7;
 assign v4642b6 = w9;
 assign w11 = vb9cfc3;
 vad119b vb8ad86 (
  .v0ef266(w0),
  .v8e8a67(w1),
  .v4642b6(w3),
  .v27dec4(w15),
  .v82de4f(w18)
 );
 vad119b v5d29b2 (
  .v0ef266(w3),
  .v8e8a67(w4),
  .v4642b6(w8),
  .v27dec4(w13),
  .v82de4f(w17)
 );
 vc4f23a vf4a6ff (
  .v985fcb(w5),
  .v4f1fd3(w14),
  .vda577d(w17),
  .v3f8943(w18),
  .v64d863(w19)
 );
 vc4f23a v9d4632 (
  .v985fcb(w6),
  .v4f1fd3(w12),
  .vda577d(w13),
  .v3f8943(w15),
  .v64d863(w16)
 );
 v84f0a1 v140dbf (
  .vee8a83(w1),
  .v03aaf0(w2),
  .vf8041d(w4),
  .v11bca5(w7),
  .vd84a57(w10)
 );
 vad119b v5c5937 (
  .v0ef266(w8),
  .v4642b6(w9),
  .v8e8a67(w10),
  .v27dec4(w12),
  .v82de4f(w14)
 );
 vad119b v3599be (
  .v4642b6(w0),
  .v8e8a67(w2),
  .v0ef266(w11),
  .v27dec4(w16),
  .v82de4f(w19)
 );
endmodule

/*-------------------------------------------------*/
/*-- AdderC-4bits  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- AdderC-4bits: Adder of two operands of 4 bits and Carry in
/*-------------------------------------------------*/
//---- Top entity
module vc3c498 (
 input [7:0] v45c6ee,
 input [7:0] v20212e,
 input vb9cfc3,
 output v4642b6,
 output [7:0] veeaa8e
);
 wire w0;
 wire w1;
 wire [0:7] w2;
 wire [0:7] w3;
 wire [0:7] w4;
 wire [0:3] w5;
 wire [0:3] w6;
 wire w7;
 wire [0:3] w8;
 wire [0:3] w9;
 wire [0:3] w10;
 wire [0:3] w11;
 assign w1 = vb9cfc3;
 assign w2 = v45c6ee;
 assign w3 = v20212e;
 assign veeaa8e = w4;
 assign v4642b6 = w7;
 v6bdcd9 v8d795a (
  .vcc8c7c(w3),
  .v651522(w10),
  .v2cc41f(w11)
 );
 v6bdcd9 v23dbc5 (
  .vcc8c7c(w2),
  .v651522(w8),
  .v2cc41f(w9)
 );
 vafb28f vef3a58 (
  .va9ac17(w4),
  .v3c88fc(w5),
  .v515fe7(w6)
 );
 va1ce30 v0ff71a (
  .v4642b6(w0),
  .vb9cfc3(w1),
  .v817794(w5),
  .v0550b6(w9),
  .v24708e(w11)
 );
 va1ce30 v12f94f (
  .vb9cfc3(w0),
  .v817794(w6),
  .v4642b6(w7),
  .v0550b6(w8),
  .v24708e(w10)
 );
endmodule

/*-------------------------------------------------*/
/*-- AdderC-8bits  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- AdderC-8bits: Adder of two operands of 8 bits and Carry in
/*-------------------------------------------------*/
//---- Top entity
module v8cc49c (
 input [7:0] vb334ae,
 input [7:0] v2b8a97,
 output [15:0] v14a530
);
 wire [0:15] w0;
 wire [0:7] w1;
 wire [0:7] w2;
 assign v14a530 = w0;
 assign w1 = v2b8a97;
 assign w2 = vb334ae;
 v8cc49c_v9a2a06 v9a2a06 (
  .o(w0),
  .i0(w1),
  .i1(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- Bus16-Join-half  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Bus16-Join-half: Join the two same halves into an 16-bits Bus
/*-------------------------------------------------*/

module v8cc49c_v9a2a06 (
 input [7:0] i1,
 input [7:0] i0,
 output [15:0] o
);
 assign o = {i1, i0};
 
endmodule
//---- Top entity
module vab13f0 (
 input [23:0] vb18564,
 output [15:0] vf0a06e,
 output [7:0] v5246f6
);
 wire [0:23] w0;
 wire [0:15] w1;
 wire [0:7] w2;
 assign w0 = vb18564;
 assign vf0a06e = w1;
 assign v5246f6 = w2;
 vab13f0_v9a2a06 v9a2a06 (
  .i(w0),
  .o1(w1),
  .o0(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- Bus24-Split-16-8  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Bus24-Split-16-8: Split the 24-bits bus into two buses of 16 and 8 wires
/*-------------------------------------------------*/

module vab13f0_v9a2a06 (
 input [23:0] i,
 output [15:0] o1,
 output [7:0] o0
);
 assign o1 = i[23:8];
 assign o0 = i[7:0];
endmodule
//---- Top entity
module v306ca3 (
 input [15:0] v91b9c1,
 output [7:0] vef5eee,
 output [7:0] vd3ef3b
);
 wire [0:15] w0;
 wire [0:7] w1;
 wire [0:7] w2;
 assign w0 = v91b9c1;
 assign vef5eee = w1;
 assign vd3ef3b = w2;
 v306ca3_v9a2a06 v9a2a06 (
  .i(w0),
  .o1(w1),
  .o0(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- Bus16-Split-half  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Bus16-Split-half: Split the 16-bits bus into two buses of the same size
/*-------------------------------------------------*/

module v306ca3_v9a2a06 (
 input [15:0] i,
 output [7:0] o1,
 output [7:0] o0
);
 assign o1 = i[15:8];
 assign o0 = i[7:0];
endmodule
//---- Top entity
module va52e3b (
 input [7:0] vf7d213,
 input [15:0] vbf8961,
 output [23:0] v6d326e
);
 wire [0:15] w0;
 wire [0:23] w1;
 wire [0:7] w2;
 assign w0 = vbf8961;
 assign v6d326e = w1;
 assign w2 = vf7d213;
 va52e3b_v9a2a06 v9a2a06 (
  .i0(w0),
  .o(w1),
  .i1(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- Bus24-Join-8-16 CLONE  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Bus24-Join-8-16: Join the two buses into an 24-bits Bus
/*-------------------------------------------------*/

module va52e3b_v9a2a06 (
 input [7:0] i1,
 input [15:0] i0,
 output [23:0] o
);
 assign o = {i1, i0};
 
endmodule
//---- Top entity
module ve108d0 (
 input v0e9572,
 input vaf813b,
 output v8f3bff,
 output v5399d1
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 assign v8f3bff = w0;
 assign v5399d1 = w1;
 assign w2 = vaf813b;
 assign w3 = v0e9572;
 ve108d0_v45bd49 v45bd49 (
  .o1(w0),
  .o0(w1),
  .sel(w2),
  .i(w3)
 );
endmodule

/*-------------------------------------------------*/
/*-- Demux-1-2  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Demultiplexor de 1 bit, de 1 a 2
/*-------------------------------------------------*/

module ve108d0_v45bd49 (
 input i,
 input sel,
 output o1,
 output o0
);
 assign {o1,o0} = i << sel;
 
endmodule
//---- Top entity
module v725b7e (
 output v9fb85f
);
 wire w0;
 assign v9fb85f = w0;
 v725b7e_vb2eccd vb2eccd (
  .q(w0)
 );
endmodule

/*-------------------------------------------------*/
/*-- 1  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Un bit constante a 1
/*-------------------------------------------------*/

module v725b7e_vb2eccd (
 output q
);
 //-- Bit constante a 1
 assign q = 1'b1;
 
 
endmodule
//---- Top entity
module vf72b3a (
 input vb186da,
 input v381ebf,
 input v50d6c6,
 output vc93bbe
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 assign w0 = v50d6c6;
 assign w1 = vb186da;
 assign w2 = v381ebf;
 assign vc93bbe = w3;
 vf72b3a_ve4e0df ve4e0df (
  .sel(w0),
  .i0(w1),
  .i1(w2),
  .o(w3)
 );
endmodule

/*-------------------------------------------------*/
/*-- Mux 2 a 1  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Multiplexor de 2 a 1
/*-------------------------------------------------*/

module vf72b3a_ve4e0df (
 input i0,
 input i1,
 input sel,
 output o
);
 //-- Multiplexor de 2 a 1, 
 //-- de 8 bits
 
 reg _o;
 
 always @(*) begin
     case(sel)
         0: _o = i0;
         1: _o = i1;
         default: _o = i0;
     endcase
 end
 
 assign o = _o;
 
endmodule
//---- Top entity
module v21cfcc (
 output v9fb85f
);
 wire w0;
 assign v9fb85f = w0;
 v21cfcc_vb2eccd vb2eccd (
  .q(w0)
 );
endmodule

/*-------------------------------------------------*/
/*-- 0  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Un bit constante a 0
/*-------------------------------------------------*/

module v21cfcc_vb2eccd (
 output q
);
 //-- Bit constante a 0
 assign q = 1'b0;
 
 
endmodule
